# URL da REST API do core
core.api.url=http://localhost:8090

# Desativa o banner do Spring Boot na consola
spring.main.banner-mode=off
# Necessário para que JavaFX e Spring Boot coexistam
spring.main.web-application-type=none
