spring.datasource.url=jdbc:postgresql://localhost:5432/kiosks_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Desativa o banner do Spring Boot na consola
spring.main.banner-mode=off
# Necessário para que JavaFX e Spring Boot coexistam
spring.main.web-application-type=none
